version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        restart: unless-stopped
        depends_on:
            - db
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    db:
        image: mongo
        container_name: db_mongo
        volumes:
        - mongodata:/data/db
        ports:
        - "27017:27017"

networks:
    nesjs-network:

volumes:
  mongodata: